# python alpine image
FROM python:3.13.1-alpine3.21
WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD [ "fastapi","dev","main.py" ,"--host","0.0.0.0"]
